---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: department-service
  name: department-service
  namespace: fireapp
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: department-service
status:
  loadBalancer: {}