---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: department-service
  name: department-service
  namespace: fireapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-service
  strategy: {}
  template:
    metadata:
      labels:
        app: department-service
    spec:
      containers:
        - image: REPOSITORY_PREFIX_ENV.azurecr.io/fireapp-department-ms:lastest
          name: department-service
          imagePullPolicy: Always
          env:
            - name: DATASOURCE_PASSWORD
              value: DATASOURCE_PASSWORD_ENV
            - name: DATASOURCE_URL
              value: DATASOURCE_URL_ENV
            - name: DATASOURCE_USERNAME
              value: DATASOURCE_USERNAME_ENV
          ports:
            - containerPort: 8080
      restartPolicy: Always
status: {}