---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: department-example
    name: department-example
    namespace: default
spec:
    ports:
        - name: "http"
          protocol: TCP
          port: 8081
          targetPort: 8081
    selector:
        App: backend
status:
    loadBalancer: {}
