---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: department-example
    name: department-example
    namespace: default
spec:
    ports:
        - name: "http"
          port: 8081
          targetPort: 8081
    selector:
        app: department-example
status:
    loadBalancer: {}
