name: Deploy project

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          image: giangh14cqt/bookaholic-backend
          push: true
          tags: giangh14cqt/bookaholic-backend:latest
      -
        name: Trigger deployment
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo docker pull giangh14cqt/bookaholic-backend:latest
            sudo docker stop bookaholic-backend
            sudo docker rm bookaholic-backend
            sudo docker run -d --name bookaholic-backend -p 8080:8080 giangh14cqt/bookaholic-backend:latest
